name: 'NoMore500'
description: 'Action that prevents 500 errors by automatically renewing expired 42OAuth tokens monthly'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  intra-id:
    description: '42Intra ID'
    required: true
  intra-pw:
    description: '42Intra PW'
    required: true
  app-url:
    description: '42OAuth App URL'
    required: true
  ssh-host:
    description: 'SSH Host'
    required: true
  ssh-private-key:
    description: 'SSH Private Key'
    required: true
  ssh-user:
    description: 'SSH User'
    required: true
  env-path:
    description: 'Path to .env file'
    required: true
  env-key:
    description: 'Key to update in .env file'
    required: true
  update-script-path:
    description: 'Path to update script'
    required: true
    default: 'no_more_500/update.sh'
runs:
  using: 'composite'
  steps:
    # Step 1: Run javascript to crawl for 42OAuth Token
    - name: Crawl for 42OAuth Token
      run: |
        npm install
        node crawling.js
      shell: bash
      env:
        INTRA_ID: ${{ inputs.intra-id }}
        INTRA_PW: ${{ inputs.intra-pw }}
        APP_URL: ${{ inputs.app-url }}

    # Step 2: setup ssh
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    # Step 3: Shell Script로 서버에 저장
    - name: Upate Token on Server
      run: |
        KEY=$(<.secret42.txt)
        UPDATE_SCRIPT=$(<${{ inputs.update-script-path }})
        ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} << EOF
          sed -i 's|${{ inputs.env-key }}=.*|${{ inputs.env-key }}=\"KEY\"|' ${{ inputs.env-path }}
          $UPDATE_SCRIPT
        EOF
      shell: bash
