name: 'NoMore500'
description: 'Action that prevents 500 errors by automatically renewing expired 42OAuth tokens monthly'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  intra-id:
    description: '42Intra ID'
    required: true
  intra-pw:
    description: '42Intra PW'
    required: true
  app-url:
    description: '42OAuth App URL'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
