name: "Test NoMore500 Action"

on:
  workflow_dispatch: # 수동 실행을 위해 설정

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Test NoMore500 Action
        uses: Rillmo/NoMore500@v1.0.4
        with:
          intra-id: ${{ secrets.INTRA_ID }}
          intra-pw: ${{ secrets.INTRA_PW }}
          app-url: ${{ secrets.APP_URL }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-user: ${{ secrets.SSH_USER }}
          env-path: ${{ secrets.ENV_PATH }}
          env-key: ${{ secrets.ENV_KEY }}
          reboot-script: 'cd ./deploy && docker-compose up -d --build'
