name: "Test NoMore500 Action"

on:
  workflow_dispatch: # 수동 실행을 위해 설정

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Test NoMore500 Action
        uses: ./ # 현재 디렉토리의 Composite Action 사용
        with:
          intra-id: ${{ secrets.INTRA_ID }}
          intra-pw: ${{ secrets.INTRA_PW }}
          app-url: ${{ secrets.APP_URL }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-user: 'ec2-user'
          env-path: './'
          env-key: 'test/.testenv'
